Add new hiffy based testing infrastructure
oxidecomputer/humility pull request #416
Opened 2023-08-30 16:55 UTC by labbott

2023-08-30 16:56 UTC, labbott commented
See https://github.com/oxidecomputer/hubris/pull/1512 for the associated hubris changes

2023-08-30 19:35 UTC, bcantrill requested changes
This looks great, and removes a bunch of gross code.  I would also like us to update the docs (which make reference to ITM -- and then have to explicitly apologize for its sporadic misbehavior), and then also bump the version.

2023-08-30 19:35 UTC, bcantrill commented on cmd/test/src/lib.rs
> +        cmd_tasks::print_tasks(
I think that this is fine for now, but we may want to stick this into a different crate if we find we're using it a bunch....

2023-09-01 18:25 UTC, bcantrill approved these changes
Looks awesome -- thank you!

2023-09-01 20:39 UTC, merged